codecov:
  max_report_age: off
  token: 56e408e0-25e7-4cc1-b03c-39a8ba42e658

comment: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 0.2
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success

ignore:
  - "**/tests"
  - "**/_version.py"
