name: intake-stac
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fsspec
  - geopandas
  - intake
  - intake-xarray
  - pytest-cov
  - rasterio
  - xarray
  - pip:
      - pystac>=1.0.0rc1
