# Intake GUI also requires jupyterlab extensions installed
# jupyter labextension install @pyviz/jupyterlab_pyviz
name: intake-stac-gui
channels:
  - conda-forge
dependencies:
  - aiohttp
  - codecov
  - coverage
  - dask
  - dask-labextension
  - datashader
  - distributed
  - gcsfs
  - geopandas
  - geoviews
  - hvplot
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-xarray
  - intake-stac
  - ipykernel
  - ipywidgets
  - jupyterlab>=3
  - matplotlib
  - nbgitpuller
  - nbsphinx
  - netcdf4
  - numpy
  - pandoc
  - panel
  - pip
  - pyproj
  - python
  - pytoml
  - pyyaml
  - pystac
  - rasterio
  - rioxarray
  - requests
  - s3fs
  - sat-search
  - sat-stac
  - scikit-image
  - xarray
